apiVersion: v1
kind: Template
metadata:
  name: payload-tracker-frontend
objects:
- apiVersion: v1
  imagePullSecrets:
  - name: quay-cloudservices-pull
  kind: ServiceAccount
  metadata:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"payload-tracker-frontend"}}'
    name: payload-tracker-frontend
  secrets:
  - name: quay-cloudservices-pull
- apiVersion: v1
  data:
    nginx.conf: "worker_processes  2;\nerror_log  /var/log/nginx/error.log warn;\n\
      pid /tmp/nginx.pid;\nevents {\n    worker_connections  1024;\n}\nhttp {\n  \
      \  include       /etc/nginx/mime.types;\n    default_type  application/octet-stream;\n\
      \    log_format main '[$time_local] \"$request\" $status $body_bytes_sent \"\
      $http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\"';\n    access_log\
      \ /var/log/nginx/access.log main;\n    sendfile        on;\n    keepalive_timeout\
      \  65;\n    server {\n        gzip on;\n        gzip_http_version 1.1;\n   \
      \     gzip_comp_level 5;\n        gzip_min_length 256;\n        gzip_proxied\
      \ any;\n        gzip_types\n        application/atom+xml\n        application/javascript\n\
      \        application/json\n        application/rss+xml\n        application/vnd.ms-fontobject\n\
      \        application/x-font-ttf\n        application/x-web-app-manifest+json\n\
      \        application/xhtml+xml\n        application/xml\n        font/opentype\n\
      \        image/svg+xml\n        image/x-icon\n        text/css\n        text/plain\n\
      \        text/x-component;\n        listen 8080;\n        disable_symlinks off;\n\
      \        root /usr/share/nginx/html;\n        location /v1 {\n             proxy_pass\
      \ ${PAYLOAD_TRACKER_URL};\n             #proxy_http_version 1.1;\n         \
      \    #proxy_set_header Upgrade $http_upgrade;\n             #proxy_set_header\
      \ Connection 'upgrade';\n             #proxy_set_header Host $host;\n      \
      \       #proxy_cache_bypass $http_upgrade;\n        }\n        location /socket.io\
      \ {\n            proxy_pass ${PAYLOAD_TRACKER_URL};\n            proxy_set_header\
      \ Upgrade $http_upgrade;\n            proxy_set_header Connection \"Upgrade\"\
      ;\n        }\n        location / {\n            try_files $uri /index.html;\n\
      \        }\n    }\n}"
  kind: ConfigMap
  metadata:
    name: payload-tracker-nginx-conf
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: payload-tracker-frontend
    name: payload-tracker-frontend
  spec:
    minReadySeconds: 15
    progressDeadlineSeconds: 600
    replicas: ${{REPLICAS}}
    revisionHistoryLimit: 9
    selector:
      matchLabels:
        app: payload-tracker-frontend
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: payload-tracker-frontend
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - payload-tracker-frontend
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - payload-tracker-frontend
                topologyKey: kubernetes.io/hostname
              weight: 99
        containers:
        - args:
          - --https-address=:8443
          - --provider=openshift
          - --openshift-service-account=payload-tracker-frontend
          - --upstream=http://localhost:8080
          - --tls-cert=/etc/tls/private/tls.crt
          - --tls-key=/etc/tls/private/tls.key
          - --cookie-secret-file=/etc/proxy/secrets/session_secret
          image: ${OAUTH_IMAGE}:${OAUTH_IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 15
            tcpSocket:
              port: 8443
            timeoutSeconds: 1
          name: payload-tracker-frontend-proxy
          ports:
          - containerPort: 8443
            name: web
            protocol: TCP
          readinessProbe:
            initialDelaySeconds: 15
            tcpSocket:
              port: 8443
            timeoutSeconds: 1
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/proxy/secrets
            name: payload-tracker-frontend-cookie
          - mountPath: /etc/tls/private
            name: payload-tracker-frontend-proxy-tls
        - image: quay.io/cloudservices/payload-tracker-frontend:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
          name: payload-tracker-frontend
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: payload-tracker-nginx-conf
            subPath: nginx.conf
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: quay-cloudservices-pull
        - name: rh-registry-pull
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: payload-tracker-frontend
        serviceAccountName: payload-tracker-frontend
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            name: payload-tracker-nginx-conf
          name: payload-tracker-nginx-conf
        - name: payload-tracker-frontend-cookie
          secret:
            defaultMode: 420
            secretName: payload-tracker-frontend-cookie
        - name: payload-tracker-frontend-proxy-tls
          secret:
            defaultMode: 420
            secretName: payload-tracker-frontend-auth
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
      service.alpha.openshift.io/serving-cert-secret-name: payload-tracker-frontend-auth
    labels:
      app: payload-tracker-frontend
    name: payload-tracker-frontend
  spec:
    ports:
    - name: proxy-port
      port: 443
      protocol: TCP
      targetPort: 8443
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: payload-tracker-frontend
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: payload-tracker-frontend
    name: payload-tracker-frontend
  spec:
    port:
      targetPort: proxy-port
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: reencrypt
    to:
      kind: Service
      name: payload-tracker-frontend
      weight: 100
    wildcardPolicy: None
parameters:
- description: Name of the Payload Tracker URL for the API
  name: PAYLOAD_TRACKER_URL
  value: http://payload-tracker-api:8000
- description: Cpu limit of service
  name: CPU_LIMIT
  value: 500m
- description: memory limit of service
  name: MEMORY_LIMIT
  value: 512Mi
- name: OAUTH_IMAGE
  value: registry.reg-aws.openshift.com:443/openshift3/oauth-proxy
- name: OAUTH_IMAGE_TAG
  value: v3.11.43
- description: The number of replicas to use for the prometheus deployment
  name: REPLICAS
  value: '1'
- description: Image tag
  name: IMAGE_TAG
  required: true
